name: atividade_2
description: "Interface + http"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  mobx: ^2.3.0
  flutter_mobx: ^2.1.0
  provider: ^6.1.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.7
  mobx_codegen: ^2.4.0
  json_serializable: ^6.7.1
